In [1]:
%load_ext autoreload
%autoreload 2

In [45]:
import typer
import sys
from pathlib import Path

# Add the parent directory of 'data_master_eng_ml' to sys.path
sys.path.append(str(Path.cwd().parent))
from typing import List
from loguru import logger
from typing import Dict
from data_master_eng_ml.config import URL_TWITCH_BASE, DUCKDB_PATH


from data_master_eng_ml.utils.helpers import (
    save_to_duckdb,
    get_unix_timestamp_for_year_start,
)

import pandas as pd

app = typer.Typer()
from data_master_eng_ml.utils.auth_igdb import IGDBAuthenticatedClient
from data_master_eng_ml.utils.api_igdb import (
    build_query,
    fetch_data_with_pagination,
)
from data_master_eng_ml.schemas.api_schemas import (
    GamesSchema,
    PlatformSchema,
    GenreSchema,
    PlayerPerspectiveSchema,
    AgeContentDescriptionSchema,
    AgeRatingSchema,
    CompaniesSchema,
    GamesModesSchema,
    LanguageSupportSchema,
    ThemeSchema,
)

In [40]:
client = IGDBAuthenticatedClient()

In [47]:
year = 2023

In [50]:
year_time = get_unix_timestamp_for_year_start(year)

## Games

In [49]:
url = f"{URL_TWITCH_BASE}/games"
fields = [
    "*",
]
filters: Dict[str, str] = {
    "first_release_date": f">= {year_time}",
}

logger.debug("Constructing the query and initiating data fetch...")
dataframe_games = fetch_data_with_pagination(
    url, build_query, fields, filters, schema=GamesSchema
)

2025-04-13 20:41:17.574 | DEBUG    | __main__:<module>:9 - Constructing the query and initiating data fetch...

KeyboardInterrupt:

In [15]:
dataframe_games

,id,artworks,category,cover,created_at,external_games,first_release_date,game_engines,game_modes,genres,...,tags,themes,updated_at,url,videos,websites,checksum,language_supports,game_status,game_type
0,240146,[103535],0,290071.0,1677669793,"[2674780, 2680022]",1677196800,[13],[1],"[32, 33]",...,"[1, 268435488, 268435489, 536874743]",[1],1744540987,https://www.igdb.com/games/boom--4,[85288],"[536247, 534823, 633779, 633780]",ac03d0dd-8816-a8d6-408a-61fb9f618fdb,"[645247, 645242, 645243, 645244, 645245, 645246]",4.0,0
1,337896,None,0,448380.0,1743528852,[2997071],1743465600,None,None,[9],...,"[268435465, 536896956, 536918309]",None,1743561635,https://www.igdb.com/games/annalynn-md,[144927],[723688],d2289d2a-7502-8abb-cffe-f63c31a670e6,None,NaN,0
2,216659,[86261],0,431088.0,1663009535,"[2994556, 2567665, 2566112]",1736294400,None,[1],"[9, 31]",...,"[268435465, 268435487, 536870984]",None,1744167162,https://www.igdb.com/games/discolored-2,"[139174, 139175, 139176]","[310371, 708332, 310372, 708333, 708334, 502908]",74ab0296-fad7-5b60-9365-f61dd76228d6,"[597459, 597461, 597463, 597464, 597465, 59746...",NaN,0
3,314239,"[153505, 153506, 153507]",0,437797.0,1724175649,"[2940851, 2979689, 2940710]",1747699200,None,"[1, 2, 3]","[13, 31]",...,"[268435469, 268435487]",None,1744507818,https://www.igdb.com/games/roadcraft,"[123367, 138943, 143864]","[665832, 665787, 665788, 665789, 665790, 66582...",b5423f5d-e862-7fc7-94c0-033d0cd65e2d,"[1074846, 1074847, 1074848, 1074849, 1074850, ...",NaN,0
4,274434,[121575],3,343685.0,1698739889,"[2857088, 2857108]",1698364800,None,None,None,...,None,None,1743782214,https://www.igdb.com/games/merge-games-horror-...,None,None,8a50d3bf-474b-029b-93c2-a34b06f2deb9,None,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50104,282334,None,5,410182.0,1704904956,None,1699574400,None,[1],[8],...,"[19, 268435464, 536872916]",[19],1743580221,https://www.igdb.com/games/number-0-iggys-castle,[108845],[620779],c6f52f5b-d8b8-e779-5dbd-cf4d37770d15,[878474],NaN,5
50105,241082,[120026],0,336492.0,1678267774,"[2862142, 2752173, 2867337, 2682101, 2682118, ...",1699920000,None,[1],"[31, 33]",...,"[1, 268435487]",[1],1744549136,https://www.igdb.com/games/ufo-robot-grendizer...,[99538],[588272],411adc61-43a1-df0a-4c44-c626b0fd8969,"[815811, 815812, 815813, 815814, 815815, 81581...",NaN,0
50106,152424,[41184],0,288563.0,1623883743,"[2686280, 2687516, 2873769, 2680277, 2062231, ...",1679961600,[13],[1],"[9, 13, 15, 32]",...,"[18, 33, 34, 268435465, 268435469, 268435471, ...","[18, 33, 34]",1744462911,https://www.igdb.com/games/terra-nil--1,"[53140, 77861, 86924, 85986, 85987, 85988]","[198008, 218154, 540260, 540261, 209035, 32873...",8e463bee-e530-e03b-776f-ad7fb0a2fb65,"[232430, 232431, 232432, 232433, 232435, 23243...",NaN,0
50107,199447,[75291],0,248226.0,1651504069,"[2623660, 2436780, 2924707, 2435557]",1719014400,None,"[1, 2, 3]","[5, 7, 32, 33]",...,"[1, 268435461, 268435463, 268435488, 268435489...",[1],1743907610,https://www.igdb.com/games/beat-hazard-3,[126344],"[279993, 279994, 324602, 673771, 324603, 32460...",6955d2ba-cc91-cc89-2143-89a38c00f495,"[215627, 215628, 215629, 215630, 215631, 21563...",NaN,0
50108,324930,[150194],1,426091.0,1733770685,"[2943831, 2943251]",1729728000,None,[1],"[13, 15]",...,"[41, 268435469, 268435471]","[18, 41]",1744423873,https://www.igdb.com/games/distant-worlds-2-re...,None,"[696951, 696952, 696953, 696954]",21d58a76-3ae6-c957-1f7b-375f3d37b7be,"[1131549, 1131550, 1131551]",NaN,1

In [ ]:
with duckdb.connect("file.db") as con:
    df_games = con.sql("SELECT * FROM raw_games").df()

## platforms

In [6]:
url = f"{URL_TWITCH_BASE}/platforms"
fields = [
    "*",
]
filters: Dict[str, str] = {}

logger.debug("Constructing the query and initiating data fetch...")
dataframe_games_platforms = fetch_data_with_pagination(
    url, build_query, fields, filters, schema=PlatformSchema
)
dataframe_games_platforms

2025-04-13 18:47:18.365 | DEBUG    | __main__:<module>:7 - Constructing the query and initiating data fetch...
2025-04-13 18:47:18.366 | INFO     | data_master_eng_ml.utils.auth_igdb:get_valid_token:82 - Token expirado ou inexistente. Obtendo um novo...
2025-04-13 18:47:19.471 | INFO     | data_master_eng_ml.utils.auth_igdb:get_token:67 - Novo token obtido com sucesso.

,id,category,created_at,generation,name,platform_logo,platform_family,slug,updated_at,url,versions,websites,checksum,platform_type,alternative_name,abbreviation,summary
0,306,1.0,1590781904,4.0,Satellaview,595.0,5.0,satellaview,1718027289,https://www.igdb.com/platforms/satellaview,[423],"[205, 289]",b9e89bb4-6962-0808-a4c0-9060c8ee9ef7,1.0,None,None,None
1,339,1.0,1595870777,4.0,Sega Pico,600.0,3.0,sega-pico,1718027289,https://www.igdb.com/platforms/sega-pico,[456],None,3166e26c-8df6-d06c-a196-2ee59c214b5a,1.0,Kids Computer Pico,None,None
2,376,1.0,1613049313,3.0,Epoch Super Cassette Vision,743.0,NaN,epoch-super-cassette-vision,1718027289,https://www.igdb.com/platforms/epoch-super-cas...,[494],[273],b84fb2e3-bfd5-df79-1a54-96baf4ec7ea9,1.0,YENO Super Cassette Vision,None,None
3,12,1.0,1297639288,7.0,Xbox 360,622.0,2.0,xbox360,1718027289,https://www.igdb.com/platforms/xbox360,"[2, 3, 495, 83]",[4],34a16af2-775f-f963-b611-406f09935eaa,1.0,X360,X360,Xbox 360 brings you a total games and entertai...
4,32,1.0,1302004506,5.0,Sega Saturn,49.0,3.0,saturn,1718027289,https://www.igdb.com/platforms/saturn,[65],[6],be49b210-4863-d0e0-31b3-fca5007a3beb,1.0,"JVC Saturn, Hi-Saturn, Samsung Saturn, V-Saturn",Saturn,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,82,3.0,1395352375,NaN,Web browser,825.0,NaN,browser,1718027354,https://www.igdb.com/platforms/browser,"[663, 662, 655, 656, 657, 658, 659, 86, 661, 660]",None,f7b1450a-fdfb-d222-f0b8-5065467be778,3.0,Internet,browser,None
215,90,6.0,1407616183,NaN,Commodore PET,543.0,NaN,cpet,1718027289,https://www.igdb.com/platforms/cpet,[103],[216],432ecbcf-48f3-8506-adeb-99f7cebac0a4,6.0,None,cpet,None
216,126,6.0,1449708680,NaN,TRS-80,372.0,NaN,trs-80,1718027289,https://www.igdb.com/platforms/trs-80,[164],None,669bc39e-cf7f-561f-415e-645888d1441e,6.0,None,None,None
217,130,1.0,1465978941,8.0,Nintendo Switch,606.0,5.0,switch,1718027289,https://www.igdb.com/platforms/switch,"[282, 173, 503]",[16],7012b5cc-0656-299b-5b76-fa97e6b1b54a,1.0,NX,Switch,None
218,159,5.0,1516801272,7.0,Nintendo DSi,246.0,5.0,nintendo-dsi,1718027289,https://www.igdb.com/platforms/nintendo-dsi,"[228, 229]",None,32fee3bb-458c-2183-32d8-61e32c64c4b3,5.0,None,None,None

In [43]:
dataframe_games_platforms.columns

Index(['id', 'category', 'created_at', 'generation', 'name', 'platform_logo',
       'platform_family', 'slug', 'updated_at', 'url', 'versions', 'websites',
       'checksum', 'platform_type', 'alternative_name', 'abbreviation',
       'summary'],
      dtype='object')

## player_perspectives

In [7]:
url = f"{URL_TWITCH_BASE}/player_perspectives"
fields = [
    "*",
]
filters: Dict[str, str] = {}

logger.debug("Constructing the query and initiating data fetch...")
dataframe_games_player_perspectives = fetch_data_with_pagination(
    url, build_query, fields, filters, schema=PlayerPerspectiveSchema
)
dataframe_games_player_perspectives

2025-04-13 18:47:34.386 | DEBUG    | __main__:<module>:7 - Constructing the query and initiating data fetch...

,id,created_at,name,slug,updated_at,url,checksum
0,1,1298968658,First person,first-person,1323289214,https://www.igdb.com/player_perspectives/first...,d90c79c9-6e5d-b0c9-49fd-3866866b8c9f
1,2,1298968673,Third person,third-person,1323289214,https://www.igdb.com/player_perspectives/third...,df3218c6-d152-af20-f352-b04f70f43ae5
2,3,1298968714,Bird view / Isometric,bird-view-slash-isometric,1582538443,https://www.igdb.com/player_perspectives/bird-...,efa5333f-98c8-654b-4d2f-34f10feb2b60
3,4,1298968735,Side view,side-view,1323289214,https://www.igdb.com/player_perspectives/side-...,54f282ed-e1d2-f821-8f29-d436138c92f2
4,5,1321295979,Text,text,1323289214,https://www.igdb.com/player_perspectives/text,472912b7-0793-021c-fdca-90bfcdf901bd
5,6,1413209511,Auditory,auditory,1582538757,https://www.igdb.com/player_perspectives/auditory,feade93b-6313-e94e-3f5d-2c15e5eadf9b
6,7,1462288484,Virtual Reality,virtual-reality,1462288484,https://www.igdb.com/player_perspectives/virtu...,2db09175-5aa1-9d30-3adc-a03e47f75b70

## genres

In [8]:
url = f"{URL_TWITCH_BASE}/genres"
fields = [
    "*",
]
filters: Dict[str, str] = {}

logger.debug("Constructing the query and initiating data fetch...")
dataframe_games_genres = fetch_data_with_pagination(
    url, build_query, fields, filters, schema=GenreSchema
)
dataframe_games_genres

2025-04-13 18:47:45.177 | DEBUG    | __main__:<module>:7 - Constructing the query and initiating data fetch...

,id,created_at,name,slug,updated_at,url,checksum
0,2,1297639288,Point-and-click,point-and-click,1323382086,https://www.igdb.com/genres/point-and-click,b295f28a-5f68-fc3e-5de2-f3195e10d160
1,4,1297639288,Fighting,fighting,1323289215,https://www.igdb.com/genres/fighting,d23da988-5bb7-011e-34dc-0b712765e470
2,5,1297639288,Shooter,shooter,1323289215,https://www.igdb.com/genres/shooter,20c255bc-ec2d-c219-34bd-47995b0a79f1
3,7,1297639288,Music,music,1323289215,https://www.igdb.com/genres/music,cbf12469-a5a8-6974-086c-ec9c6aeb5791
4,8,1297639288,Platform,platform,1323289215,https://www.igdb.com/genres/platform,06c188b9-1058-933f-dfee-4ec658117ad2
5,9,1297639288,Puzzle,puzzle,1323289215,https://www.igdb.com/genres/puzzle,f4afdd14-b8c5-e938-58a6-ff0a56514f8b
6,10,1297639288,Racing,racing,1323289215,https://www.igdb.com/genres/racing,41227287-0a1a-0f14-90f2-05655314e8b4
7,11,1297639288,Real Time Strategy (RTS),real-time-strategy-rts,1323289215,https://www.igdb.com/genres/real-time-strategy...,f4e875ed-3c04-6fbe-a600-bbea74ed1025
8,12,1297639288,Role-playing (RPG),role-playing-rpg,1323289215,https://www.igdb.com/genres/role-playing-rpg,5a7bd431-149a-3083-532d-2176f4daca24
9,13,1297639288,Simulator,simulator,1323289215,https://www.igdb.com/genres/simulator,00cd9e3e-ef6b-c1c1-387e-cdfcfdc05dd0
10,14,1297639288,Sport,sport,1323289215,https://www.igdb.com/genres/sport,ae972fd1-328e-08f9-1ce2-340badc1024e
11,15,1297639288,Strategy,strategy,1323289215,https://www.igdb.com/genres/strategy,a722bf83-aa16-da39-6cbf-709bcfd5c0be
12,16,1297678340,Turn-based strategy (TBS),turn-based-strategy-tbs,1323289215,https://www.igdb.com/genres/turn-based-strateg...,34acc979-404f-f6b2-dc55-3a6f06e6dad6
13,24,1300991933,Tactical,tactical,1323289215,https://www.igdb.com/genres/tactical,f13e2375-3258-bc0c-931b-d7f41f6ca81d
14,25,1301647919,Hack and slash/Beat 'em up,hack-and-slash-beat-em-up,1323289215,https://www.igdb.com/genres/hack-and-slash-bea...,6c84d75f-abcb-cf79-dea9-853eb738d178
15,26,1301989734,Quiz/Trivia,quiz-trivia,1323289215,https://www.igdb.com/genres/quiz-trivia,e51ba5a9-8862-fdb6-480f-59e9e8b813df
16,30,1320266606,Pinball,pinball,1323289215,https://www.igdb.com/genres/pinball,01f4c9a7-4893-54ad-7b83-8ec8ee97d298
17,31,1323568041,Adventure,adventure,1323568041,https://www.igdb.com/genres/adventure,a93a77df-3927-13fa-1d50-5d443cbb695f
18,32,1341431954,Indie,indie,1341431954,https://www.igdb.com/genres/indie,8a712b9c-3041-638e-98ae-072760af9611
19,33,1380971449,Arcade,arcade,1380971449,https://www.igdb.com/genres/arcade,cd4431bf-5482-b058-a863-7eb596a438dd
20,34,1571844717,Visual Novel,visual-novel,1571844717,https://www.igdb.com/genres/visual-novel,cdc342d3-0a7b-e74f-f4ec-9145e6682a51
21,35,1588855092,Card & Board Game,card-and-board-game,1588855092,https://www.igdb.com/genres/card-and-board-game,c26cae4e-ecb3-06a9-f46f-245c1da067c8
22,36,1588855126,MOBA,moba,1588855126,https://www.igdb.com/genres/moba,c0ca4862-b90a-1aa0-e77f-c0b5c7eb0245

## themes

In [10]:
url = f"{URL_TWITCH_BASE}/themes"
fields = [
    "*",
]
filters: Dict[str, str] = {}

logger.debug("Constructing the query and initiating data fetch...")
dataframe_themes = fetch_data_with_pagination(
    url, build_query, fields, filters, schema=ThemeSchema
)
dataframe_themes

2025-04-13 18:48:17.343 | DEBUG    | __main__:<module>:7 - Constructing the query and initiating data fetch...

,id,created_at,name,slug,updated_at,url,checksum
0,31,1323610197,Drama,drama,1323610197,https://www.igdb.com/themes/drama,a10308c4-a660-7016-742b-ec956e9e9675
1,32,1323635380,Non-fiction,non-fiction,1323635380,https://www.igdb.com/themes/non-fiction,64d7a553-bbf8-1bbb-fc3c-8b1f7e404f5e
2,33,1326545059,Sandbox,sandbox,1326545059,https://www.igdb.com/themes/sandbox,e2f2c5b2-16ea-6e44-e2bb-af500d0b3f97
3,34,1326829751,Educational,educational,1326829751,https://www.igdb.com/themes/educational,91f581b0-62df-6d68-b7fc-1d4f1bc6d4fa
4,35,1326829940,Kids,kids,1326829940,https://www.igdb.com/themes/kids,95416d52-fb76-9995-f035-ee86bafbe5c4
5,38,1345486426,Open world,open-world,1345486426,https://www.igdb.com/themes/open-world,3417947f-3f76-24e3-fc7b-ce2a804d448a
6,39,1345493134,Warfare,warfare,1345493134,https://www.igdb.com/themes/warfare,361067f4-c398-2b0b-6c51-8b3132372658
7,40,1356889401,Party,party,1356889401,https://www.igdb.com/themes/party,8eb5e994-f11e-210a-f2f3-9eb70bc72dc9
8,41,1357170973,"4X (explore, expand, exploit, and exterminate)",4x-explore-expand-exploit-and-exterminate,1357170973,https://www.igdb.com/themes/4x-explore-expand-...,5fb7667b-bd1e-3e9c-4be6-11136847d5ab
9,42,1463742381,Erotic,erotic,1463742381,https://www.igdb.com/themes/erotic,4eaf0aee-fa6d-02a9-2694-3f74fd14451f
10,43,1465256057,Mystery,mystery,1465256057,https://www.igdb.com/themes/mystery,0833bd75-8288-33d2-a6f0-0ad34e789cfa
11,1,1322605337,Action,action,1323289216,https://www.igdb.com/themes/action,cee4e3c1-6b2d-6dcc-a707-e00ca4de6ecc
12,17,1322605338,Fantasy,fantasy,1323289216,https://www.igdb.com/themes/fantasy,e24dc205-20ff-01fc-00eb-d7a460ad600b
13,18,1322605338,Science fiction,science-fiction,1323289216,https://www.igdb.com/themes/science-fiction,6aebdd69-6e6e-61f3-4721-3eb222712062
14,19,1322605338,Horror,horror,1323289216,https://www.igdb.com/themes/horror,4775a860-da15-e363-9bbd-b944f7a90ab9
15,20,1322605338,Thriller,thriller,1323289216,https://www.igdb.com/themes/thriller,2e91259e-a1bd-d0a8-474c-de2a29ee0dd4
16,21,1322605338,Survival,survival,1323289216,https://www.igdb.com/themes/survival,9dda17f7-c26b-bf97-40d1-4fbff9f1fa4b
17,22,1322605338,Historical,historical,1323289216,https://www.igdb.com/themes/historical,055d8eb9-e32a-35b5-22b6-05f33f883ae3
18,23,1322605338,Stealth,stealth,1323289216,https://www.igdb.com/themes/stealth,71cc79cc-2055-baa3-0d08-b6136ae5c3fa
19,27,1322605339,Comedy,comedy,1323289216,https://www.igdb.com/themes/comedy,81df3ee7-c23d-b87f-36b5-e2a3279d45de
20,28,1322605339,Business,business,1323289216,https://www.igdb.com/themes/business,0be76b08-2fb9-7de1-e8ef-bcd32fe76519
21,44,1588855294,Romance,romance,1588855294,https://www.igdb.com/themes/romance,8c40b73c-c673-3e26-6d53-69d01476f473

## companies

In [7]:
fields_names = list(CompaniesSchema.model_json_schema()["properties"].keys())

In [8]:
url = f"{URL_TWITCH_BASE}/companies"
fields = fields_names
filters: Dict[str, str] = {}

logger.debug("Constructing the query and initiating data fetch...")
dataframe_companies = fetch_data_with_pagination(
    url, build_query, fields, filters, schema=CompaniesSchema
)
dataframe_companies

2025-04-13 19:00:40.846 | DEBUG    | __main__:<module>:5 - Constructing the query and initiating data fetch...

,id,change_date_category,country,created_at,description,developed,name,slug,start_date,start_date_category,updated_at,url,websites,checksum,status,logo,published
0,61668,7,840.0,1739687269,CyrustheVirus Studios was established by Sheld...,[289276],CyrusTheVirus Studios,cyrusthevirus-studios,1.548979e+09,0,1739987957,https://www.igdb.com/companies/cyrusthevirus-s...,[13818],95dac7b6-f88b-6715-f88a-beac4da5d751,0.0,NaN,None
1,61715,7,NaN,1739887282,None,None,FATHILLL GAMES,fathilll-games,NaN,7,1739888154,https://www.igdb.com/companies/fathilll-games,None,5b8b9411-4f75-ab72-a294-2d339e9d2883,0.0,NaN,None
2,30720,7,203.0,1609096608,300AD is an independent company associating de...,"[80245, 52452, 144481, 142326, 142325, 144511,...",300AD,300ad,NaN,7,1609576801,https://www.igdb.com/companies/300ad,[4031],8d82f741-09a6-90f9-491d-91009e2dd43f,0.0,3995.0,None
3,540,2,276.0,1317748979,10TACLE STUDIOS was specialized in the develop...,[92755],10tacle Studios,10tacle-studios,1.072829e+09,2,1739988114,https://www.igdb.com/companies/10tacle-studios,None,4f819d88-70f7-ddb0-2751-08cd28130f51,1.0,1902.0,"[736, 738, 11286, 15762, 27466, 125168, 21516,..."
4,62963,7,NaN,1744336484,None,None,NoShadow,noshadow,NaN,7,1744336484,https://www.igdb.com/companies/noshadow,None,3ce3ec4e-aa95-280e-9971-83d44ace1e65,0.0,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59159,7466,7,752.0,1449608774,Paradox Development Studio is based on the her...,"[17023, 10397, 10400, 10401, 10285, 10283, 192...",Paradox Development Studio,paradox-development-studio,7.889184e+08,0,1744129207,https://www.igdb.com/companies/paradox-develop...,[1200],fe5695ba-6875-720a-4152-1bbeee6a11cf,0.0,796.0,None
59160,11925,7,840.0,1484290066,Headcannon is a Los Angeles-based software dev...,"[21062, 112897, 206597, 141532, 94873, 25684, ...",Headcannon,headcannon,NaN,7,1740001969,https://www.igdb.com/companies/headcannon,[936],074bbe9e-9f61-61a4-6ae9-378aef55444f,0.0,1181.0,"[141532, 170662, 326813, 301516]"
59161,37730,7,840.0,1632315402,"Apogee Entertainment, formerly Apogee Software...",[249036],Apogee Entertainment,apogee-entertainment,1.215994e+09,0,1740253776,https://www.igdb.com/companies/apogee-entertai...,[10358],00b566de-9b87-2d43-7c4b-7462e905e285,0.0,12274.0,"[123877, 215773, 218098, 204524, 197046, 25235..."
59162,61707,7,NaN,1739832088,None,[331973],The Snake Soup,the-snake-soup,NaN,7,1739838638,https://www.igdb.com/companies/the-snake-soup,None,5d3bf746-064c-17e7-ae10-c73e5c85a5c3,0.0,NaN,[331973]
59163,1277,2,840.0,1374615281,Mattel Interactive (Known as Mattel Media unti...,"[8014, 18244, 26688, 313290, 58643]",Mattel Interactive,mattel-interactive,8.240832e+08,0,1744011200,https://www.igdb.com/companies/mattel-interactive,None,8542f349-fd8e-84f8-0fce-ceec1a8c2a60,1.0,13309.0,"[3313, 5653, 8014, 8091, 2714, 143442, 3447, 4..."

## age_ratings

In [37]:
url = f"{URL_TWITCH_BASE}/age_ratings"
fields = [
    "*",
]
filters: Dict[str, str] = {}

logger.debug("Constructing the query and initiating data fetch...")
dataframe_age_ratings = fetch_data_with_pagination(
    url, build_query, fields, filters, schema=None
)
dataframe_age_ratings

2025-04-13 20:24:56.064 | DEBUG    | __main__:<module>:7 - Constructing the query and initiating data fetch...

,id,category,content_descriptions,rating,checksum,organization,rating_category,rating_content_descriptions,synopsis
0,94924,3,[98985],15,253dddef-d8ae-a69b-3b16-eeb1abac620b,3,15,[65],NaN
1,202059,5,[183275],24,90003678-9f97-8be6-89a4-c58c66c31923,5,24,[69],NaN
2,161368,6,"[147374, 147375]",31,f7659d86-8ff8-2701-2f71-81883483ce24,6,31,"[84, 75]",NaN
3,207012,5,[186489],25,6bfc501a-0f78-ad44-c8ab-cc20b052a37d,5,25,[68],NaN
4,76012,1,[78426],8,2c32a73f-8621-139a-f7ff-7f78e92457d2,1,3,[6],NaN
...,...,...,...,...,...,...,...,...,...
162390,203548,1,"[184090, 184089, 184091, 184092, 184093, 184094]",11,652ecfe8-d587-8c38-e155-07fb35fd6b3e,1,6,"[14, 10, 8, 18, 4, 21]",NaN
162391,203656,5,"[184141, 184142]",25,35e8fea9-c028-6cea-8257-6b06dd68fe16,5,25,"[72, 69]",NaN
162392,203584,1,[184115],8,d47aa02a-d948-c678-e3b0-436697307a6b,1,3,[47],NaN
162393,203659,1,"[184145, 184146, 184147, 184148, 184149]",11,2af3c841-281a-4a33-4ee3-c41061583733,1,6,"[18, 10, 14, 4, 11]",NaN
162394,203553,1,"[184096, 184097, 184098]",10,db8bae1a-7606-e6cf-a6d2-ae5f951f2cb6,1,5,"[29, 11, 38]",NaN

## languages

In [8]:
url = f"{URL_TWITCH_BASE}/languages"
fields = [
    "*",
]
filters: Dict[str, str] = {}

logger.debug("Constructing the query and initiating data fetch...")
dataframe_languages = fetch_data_with_pagination(
    url, build_query, fields, filters, schema=LanguageSupportSchema
)
dataframe_languages

2025-04-13 19:08:53.664 | DEBUG    | __main__:<module>:7 - Constructing the query and initiating data fetch...

,id,created_at,name,native_name,locale,updated_at,url,checksum
0,1,1664803639,Arabic,العربية,ar,1664803639,None,e0963ddc-1e01-32e2-a959-d5ccda50410c
1,2,1664803639,Chinese (Simplified),简体中文,zh-CN,1664803639,None,ddcc7457-8939-17a3-9826-ef92d0d72371
2,3,1664803639,Chinese (Traditional),繁體中文,zh-TW,1664803639,None,e7a793e9-d117-bc98-a000-67e444c0893d
3,4,1664803639,Czech,čeština,cs-CZ,1664803639,None,58621751-aa00-f068-dbaf-2369d2e5a015
4,5,1664803639,Danish,Dansk,da-DK,1664803639,None,613fc1f9-9c07-474a-1ad5-7a26b44cc7ea
5,6,1664803639,Dutch,Nederlands,nl-NL,1664803639,None,a22e453a-e539-b794-5d44-368fbe6e3770
6,7,1664803639,English,English (US),en-US,1664803639,None,e2f64b8d-425f-28a3-3552-217aa1a955eb
7,8,1664803639,English (UK),English (UK),en-GB,1664803639,None,9239bea3-9b7a-e4d2-016e-43440fbf8866
8,9,1664803639,Spanish (Spain),Español (España),es-ES,1664803639,None,62657819-b6f2-2beb-786e-78455af2de8f
9,10,1664803639,Spanish (Mexico),Español (Mexico),es-MX,1664803639,None,a94bcdc1-6434-c7b2-d9ce-14976388609c
10,12,1664803639,French,Français,fr-FR,1664803639,None,6a477f36-9248-eae8-6626-5932d6384dbe
11,14,1664803639,Hungarian,Magyar,hu-HU,1664803639,None,362d33d4-4896-3e8d-b703-cc030c2c7f73
12,11,1664803639,Finnish,Suomi,fi-FI,1664803639,None,863a2d01-e473-e98b-159c-4049d2216012
13,15,1664803639,Italian,Italiano,it-IT,1664803639,None,52074797-ab02-c337-a805-a3e9969fc0eb
14,13,1664803639,Hebrew,עברית,he-IL,1664803639,None,4102be99-eedf-5c3f-863c-d118637f7bf1
15,16,1664803639,Japanese,日本語,ja-JP,1664803639,None,6e46a214-1fc9-e097-bf2b-b5d3f1187a48
16,17,1664803639,Korean,한국어,ko-KR,1664803639,None,9ba648bf-f5fa-fa3c-3c6a-2fc7e1510cd6
17,18,1664803639,Norwegian,Norsk,nb-NO,1664803639,None,68196f0b-fdc4-c8cc-ded7-439904183360
18,20,1664803639,Portuguese (Portugal),Português (Portugal),pt-PT,1664803639,None,0ba51fb0-09a1-8603-583d-0c0f635854c4
19,21,1664803639,Portuguese (Brazil),Português (Brasil),pt-BR,1664803639,None,c62e5a15-99dc-0cd8-de04-fe6021ca78f8
20,19,1664803639,Polish,Polski,pl-PL,1664803639,None,19ec0e97-56cc-dc50-54fa-e2dd3989ba11
21,22,1664803639,Russian,Русский,ru-RU,1664803639,None,a9cb4d56-9180-df0b-cd5f-ad8c9b820b64
22,24,1664803640,Turkish,Türkçe,tr-TR,1664803640,None,3fa287a0-7ee0-f965-2282-93931077359c
23,25,1664803640,Thai,ไทย,th-TH,1664803640,None,ec633fe7-383e-7831-7335-136cd446f771
24,26,1664803640,Vietnamese,Tiếng Việt,vi-VN,1664803640,None,b576a1df-38ab-7aa5-60b4-090c09be22e0
25,23,1664803639,Swedish,Svenska,sv-SE,1664803639,None,37988d2f-f5e5-663c-8cc5-5c27f463effe
26,27,1666085793,German,Deutsch,de-DE,1666085793,None,fc4eae54-cc3c-bcaa-bbc8-580c87d5951c
27,28,1666085871,Ukrainian,українська,uk-UA,1666085871,None,0030d38e-0f5a-1ce0-f3f0-0a99fac33b0f

## age_rating_content_descriptions_v2

In [12]:
url = f"{URL_TWITCH_BASE}/age_rating_content_descriptions_v2"
fields = [
    "*",
]
filters: Dict[str, str] = {}

logger.debug("Constructing the query and initiating data fetch...")
dataframe_age_rating_content_descriptions = fetch_data_with_pagination(
    url, build_query, fields, filters, schema=AgeContentDescriptionSchema
)
dataframe_age_rating_content_descriptions

2025-04-13 19:15:36.145 | DEBUG    | __main__:<module>:7 - Constructing the query and initiating data fetch...

,id,description,organization,created_at,updated_at,checksum
0,19,Sexual Violence,1,1741259102,1741259102,20de5149-8b45-e984-8dee-e62ac7ae8071
1,20,Simulated Gambling,1,1741259102,1741259102,ce2f745f-3bf9-4ae9-6bb9-1fbaba4a1a14
2,25,Tobacco Reference,1,1741259102,1741259102,20d3cf4f-e6b3-e9af-39bc-70ea49d01748
3,26,Use of Alcohol,1,1741259102,1741259102,4eed64dc-3e3c-bcd5-8e19-ea0794ce35be
4,23,Strong Sexual Content,1,1741259102,1741259102,dca75ad4-e0ea-f3d4-9c84-d4a31412f37f
...,...,...,...,...,...,...
80,72,"Alcohol, Tobacco, Drug",5,1741259103,1741259103,3500ec0a-f029-f8cd-e265-23d2028bcb57
81,73,"Crime, Anti-Social",5,1741259103,1741259103,20319269-0cad-ceb0-017f-62e87bfb31c3
82,74,Gambling,5,1741259103,1741259103,451ecb4b-2376-d24c-97c8-48e6e9ecf3e3
83,78,Nudez (Nudity),6,1741259103,1741259103,ca2e9c7e-d6d9-a23a-9be6-18dc44712506
84,79,Sexo (Sex),6,1741259103,1741259103,bad5fd2a-4a8c-afcf-a17d-ade68c36a9a5

## game_modes

In [13]:
url = f"{URL_TWITCH_BASE}/game_modes"
fields = [
    "*",
]
filters: Dict[str, str] = {}

logger.debug("Constructing the query and initiating data fetch...")
dataframe_games_modes = fetch_data_with_pagination(
    url, build_query, fields, filters, schema=GamesModesSchema
)
dataframe_games_modes

2025-04-13 19:16:09.488 | DEBUG    | __main__:<module>:7 - Constructing the query and initiating data fetch...

,id,created_at,name,slug,updated_at,url,checksum
0,1,1298968834,Single player,single-player,1323289216,https://www.igdb.com/game_modes/single-player,1cc07088-c5fb-3cb2-9e68-af6620c18836
1,2,1298968853,Multiplayer,multiplayer,1323289216,https://www.igdb.com/game_modes/multiplayer,3ffef62b-e19f-6bab-d510-98385c06d902
2,3,1298968887,Co-operative,co-operative,1323289216,https://www.igdb.com/game_modes/co-operative,d154173b-5bdf-5fda-5969-e4c87e135d1a
3,4,1298968900,Split screen,split-screen,1323289216,https://www.igdb.com/game_modes/split-screen,a165517f-f166-79cb-1290-d8c8d4f157a8
4,5,1298969041,Massively Multiplayer Online (MMO),massively-multiplayer-online-mmo,1323289216,https://www.igdb.com/game_modes/massively-mult...,631ae92b-e28d-8089-dd44-48cd2febf4ea
5,6,1588855506,Battle Royale,battle-royale,1588855506,https://www.igdb.com/game_modes/battle-royale,bf9864c2-5d73-bc3a-c90b-3da8debd3292

## Get Raw Data

In [51]:
raw_api_tables_schemas = {
    "raw_games": GamesSchema,
    "raw_platforms": PlatformSchema,
    "raw_player_perspectives": PlayerPerspectiveSchema,
    "raw_genres": GenreSchema,
    "raw_themes": ThemeSchema,
    "raw_companies": CompaniesSchema,
    "raw_age_ratings": AgeRatingSchema,
    "raw_languages": LanguageSupportSchema,
    "raw_age_rating_content_descriptions": AgeContentDescriptionSchema,
    "raw_game_modes": GamesModesSchema,
}

In [ ]:
for table, schema in raw_api_tables_schemas.items():
    # Get the endpoint name from the description
    endpoint_name = schema.model_json_schema()["description"].split(" ")[-2]

    # Get the fields from the schema
    fields = list(schema.model_json_schema()["properties"].keys())
    # Construct the filters
    if schema == GamesSchema:
        filters = {
            "first_release_date": f">= {year_time}",
        }
    else:
        # For other schemas, we can set filters to an empty dictionary
        filters = {}

    # Request the data from the API
    url = f"{URL_TWITCH_BASE}/{endpoint_name}"
    logger.debug(
        f"Constructing the query and initiating data fetch for {endpoint_name}..."
    )
    logger.debug(f"URL: {url}")
    logger.debug(f"Fields: {fields}")
    logger.debug(f"Filters: {filters}")
    logger.debug(f"Schema: {schema.__name__}")
    # Fetch the data from the API
    dataframe = fetch_data_with_pagination(
        url, build_query, fields, filters, schema=schema
    )

    # Save the DataFrame to DuckDB
    save_to_duckdb(dataframe, table, DUCKDB_PATH)
    logger.debug(f"Data fetched from {endpoint_name} and saved to table '{table}'.")

    logger.info(
        f"Completed processing for table: {table} using schema: {schema.__name__}"
    )

2025-04-13 20:42:16.050 | DEBUG    | __main__:<module>:18 - Constructing the query and initiating data fetch for games...
2025-04-13 20:42:16.050 | DEBUG    | __main__:<module>:21 - URL: https://api.igdb.com/v4/games
2025-04-13 20:42:16.050 | DEBUG    | __main__:<module>:22 - Fields: ['id', 'artworks', 'category', 'cover', 'created_at', 'external_games', 'first_release_date', 'game_engines', 'game_modes', 'genres', 'keywords', 'name', 'platforms', 'player_perspectives', 'release_dates', 'screenshots', 'similar_games', 'slug', 'status', 'summary', 'tags', 'themes', 'updated_at', 'url', 'videos', 'websites', 'checksum', 'language_supports', 'game_status', 'game_type']
2025-04-13 20:42:16.050 | DEBUG    | __main__:<module>:23 - Filters: {'first_release_date': '>= 1672542000'}
2025-04-13 20:42:16.050 | DEBUG    | __main__:<module>:24 - Schema: GamesSchema